# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('maxplayers', models.IntegerField(default=4)),
                ('content', models.TextField(max_length=2000)),
                ('time_start', models.DateTimeField()),
                ('time_finish', models.DateTimeField()),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
    ]
